packages:
  - backend
  - frontend

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  mongodb-memory-server: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - playwright
